services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: skillstracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skillstracker"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./BackendSkillTracker
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/config/config.yaml
    ports:
      - "8081:8080"
    restart: always
    volumes:
      - ./BackendSkillTracker/config:/app/config
      - ./BackendSkillTracker/uploads:/app/uploads

  frontend:
    build:
      context: ./FrontendSkillTracker
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:
