env: dev #local, dev, prod
jwt_secret: andrey
http_server:
  port: :8080
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 60s
database:
  dsn: "postgres://postgres:12345678@db:5432/skillstracker?sslmode=disable"
  host: db
  port: 5432
  user: postgres
  password: 12345678
  name: skillstracker
  sslmode: disable